DRAFT: Add badge model and database interaction
scribeWiz-team/ScribeWiz pull request #107
Opened 2023-05-12 00:01 UTC by Netzu00

So far, the model has been added, and a test badge can be added to the user's badge collection in the database by clicking the ScribeWiz logo button in profile page. The intended use of the button is to bring up a window that displays the user's badge collection, which will be added eventually.

2023-05-17 21:58 UTC, Netzu00 commented
Added the badge collection window, which displays the badges associated to the currently logged in user (badge data taken from the database). Badges have 3 different ranks (Gold, Silver, Bronze), which will change the color of their card in the collection. 
Additionally, added functions to upload and download musicxml files to and from the database.

2023-05-18 10:08 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/BadgeDisplayActivity.kt
> +    fun badgeDisplayLayout(){
```suggestion
    fun BadgeDisplayLayout(){
```

2023-05-18 10:09 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/BadgeDisplayActivity.kt
> +            badgeDisplayLayout()
```suggestion
            BadgeDisplayLayout()
```

2023-05-18 10:10 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/BadgeDisplayActivity.kt
> +            displayBadges()
```suggestion
            Badges()
```

2023-05-18 10:10 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/Activities/BadgeDisplayActivity.kt
> +    fun displayBadges(){
```suggestion
    fun Badges(){
```

2023-05-18 10:14 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
> +                        db.collection("Users")
```suggestion
                        db.collection(UserModel.COLLECTION)
```

2023-05-18 10:17 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
> +            var badgeData = BadgeModel(
you can put it as a default value in the parameters of the function instead, 
Like:
```
fun addBadgeToUser(user: UserModel, badge: BadgeModel = BadgeModel(...)) {
...
```

2023-05-18 10:18 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
> +                .collection("Users")
```suggestion
                .collection(UserModel.COLLECTION)
```

2023-05-18 10:18 UTC, NoeTerrier commented on app/src/main/java/com/github/scribeWizTeam/scribewiz/models/BadgeModel.kt
> +            userDoc.collection("Badges")
```suggestion
            userDoc.collection(COLLECTION)
```

2023-05-18 10:19 UTC, NoeTerrier requested changes
May need to do minor changes before merging :)

2023-05-18 12:31 UTC, Netzu00 reviewed
Thank you for the review! I've made the changes :)

2023-05-18 12:44 UTC, NoeTerrier approved these changes

2023-05-18 15:15 UTC, merged